tabela_regras_gramatica  = {
    #numero da regra: (regra esquerda, regra direita, quantidade de simbolos)
    1: ("P'", "P", 1),
    2: ("P", "inicio V A", 3),
    3: ("V", "varincio LV", 2),
    4: ("LV", "D LV", 2),
    5: ("LV", "varfim ptv", 2),
    6: ("D", "L TIPO ptv", 3),
    7: ("L", "id vir L", 3),
    8: ("L", "id", 1),
    9: ("TIPO", "int", 1),
    10: ("TIPO", "real", 1),
    11: ("TIPO", "lit", 1),
    12: ("A", "ES A", 2),
    13: ("ES", "leia id ptv", 3),
    14: ("ES", "escreva ARG ptv", 3),
    15: ("ARG", "literal", 1),
    16: ("ARG", "num", 1),
    17: ("ARG", "id", 1),
    18: ("A", "CMD A", 2),
    19: ("CMD", "id rcb LD ptv", 4),
    20: ("LD", "OPRD opm OPRD", 3),
    21: ("LD", "OPRD", 1),
    22: ("OPRD", "id", 1),
    23: ("OPRD", "num", 1),
    24: ("A", "COND A", 2),
    25: ("COND", "CAB CP", 2),
    26: ("CAB", "se ab_p EXP_R fc_p então", 5),
    27: ("EXP_R", "OPRD opr OPRD", 3),
    28: ("CP", "ES CP", 2),
    29: ("CP", "CMD CP", 2),
    30: ("CP", "COND CP", 2),
    31: ("CP", "fimse", 1),
    32: ("A", "R A", 2),
    33: ("R", "faca_ate ab_p EXP_R fc_p CP_R", 5),
    34: ("CP_R", "ES CP_R", 2),
    35: ("CP_R", "CMD CP_R", 2),
    36: ("CP_R", "COND CP_R", 2),
    37: ("CP_R", "fimfaca", 1),
    38: ("A", "fim", 1)
}

converte_token = {
        "inicio": 'inicio',
        "varinicio": 'varinicio',
        "varfim": 'varfim',
        "escreva": 'escreva',
        "leia": 'leia',
        "se": 'se',
        "entao": 'entao',
        "fimse": 'fimse',
        "faca_ate": 'faca_ate',
        "fimfaca": 'fimfaca',
        "fim": 'fim',
        "inteiro": 'int',
        "literal": 'lit',
        "real": 'real',
        "NUM": 'num',
        "LIT": 'literal', 
        "ID": 'id',
        "EOF": '$',
        "OPR": 'opr',
        "RCB": 'rcb',
        "OPM": 'opm',
        "AB_P": 'ab_p',
        "FC_P": 'fc_p',
        "PT_V": 'ptv',
        "VIR": 'vir'
    }